note:
  'Make sure to rename the file to config.yaml not config_template.yaml'

servers: 
  - host: 'play.kaboom.pw'
    port: 25565
    core: true
    
  - host: 'chipmunk.land'
    port: 25565
    core: true

  - host: 'nekoboom.bongocatsmp.site'
    port: 25565
    core: true

    
selfcare:
  prefix: '&8[&aPrefix: &2}&8]'

scheme:
  publicColor: "#cf8ccb"
  trustedColor: "#77519c"
  ownerColor: "#bd0259"
  consoleColor: "#7b76b0"

  defaultColor: '#b69bcf'
  unknownColor: '#94475a'
  errorColor: '#96082e'
  successColor: '#99c995'

bot:
  version: 1.20.4
  perversion: 0.0.2
  chatLogging: true

  keys:
    owner: 'Owner key here'
    trusted: 'Trusted key here'

prefixes: 
  [
    "}",
    "{",
    ",",
    "[",
    "]",
    "qbot:",
    "qbot!",
    ";",
    "¬",
    "pizza:",
    "piza:",
    "Ξ"
  ]

core:

  block: repeating_command_block
  type: destroy

  start:
    x: 0
    y: 0
    z: 0
  end:
    x: 15
    y: 0
    z: 15